### ISSUE TITLE
Support SPIKE - Virtual Edition system

### ISSUE THREAD

**Issue by ProbablyManuel** [ProbablyManuel/requiem#164]
SPIKE - Virtual Edition are a bunch of keywords injected into `Update.esm` that are primarily used by Guard Dialogue Overhaul to trigger lines for wearing certain items.

### Expected Outcome

- SPIKE keywords are copied into Requiem.esp.
- SPIKE keyword additions to weapons and armors are forwarded.
- Weapons and armors added by Requiem have appropriate SPIKE keywords.

**Comment by DefinitelyNotJT** [comment]
Just made a merge request with these forwarded in a new esp, along with some "missing" survival keywords, etc. 

As I was making the plugin, it occurred to me that these days this kind of thing would be better handled by KID, but I guess since Requiem is overwriting all these vanilla entries anyway, having them in the plugin doesn't hurt either.
